/*
* Copyright 2021 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this 
* software and associated documentation files (the "Software"), to deal in the Software 
* without restriction, including without limitation the rights to use, copy, modify, merge, 
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons 
* to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or 
* substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
package com.ale.o2g;


import java.util.Collection;

import com.ale.o2g.internal.services.IService;
import com.ale.o2g.types.comlog.ComRecord;
import com.ale.o2g.types.comlog.Page;
import com.ale.o2g.types.comlog.QueryFilter;
import com.ale.o2g.types.comlog.QueryResult;

/**
 * The {@code CommunicationLogService} provides operations to retrieve, manage,
 * and manipulate a user's communication log (com records).
 * <p>
 * Accessing this service requires a <b>TELEPHONY_ADVANCED</b> license.
 * <p>
 * Communication records are generated by the O2G server and provide detailed
 * information about calls, participants, call outcomes, and durations.
 * <p>
 * Most methods support sessions opened either by a regular user or by an
 * administrator. If a session is opened for a user, the {@code loginName} parameter
 * is ignored. If the session is opened by an administrator, {@code loginName} is
 * required to specify the target user.
 *
 */
public interface CommunicationLogService extends IService {

    /**
     * Retrieves communication records based on the specified {@link QueryFilter},
     * with pagination support and optional optimization.
     * <p>
     * If {@code optimized} is {@code true}, the full identity of a participant is
     * returned only the first time it appears in the records. Subsequent occurrences
     * of the same participant will only include minimal identification (e.g., phone number).
     * <p>
     * The {@link Page} parameter allows querying the communication log page by page.
     * The returned {@link QueryResult} includes the records, paging information, and
     * the total number of matching records.
     * 
     * @param filter    the filter describing the query criteria
     * @param page      the page description
     * @param optimized {@code true} to enable optimization
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return a {@link QueryResult} containing the matching com records, or {@code null} in case of error
     */
    QueryResult getComRecords(QueryFilter filter, Page page, boolean optimized, String loginName);

    /**
     * Retrieves communication records based on the specified filter and page,
     * with optional optimization.
     * <p>
     * For sessions opened by a user, {@code loginName} is not required. This
     * method will return {@code null} if invoked from an administrator session.
     * 
     * @param filter    the filter describing the query criteria
     * @param page      the page description
     * @param optimized {@code true} to enable optimization
     * @return a {@link QueryResult} containing the matching com records, or {@code null} otherwise
     */
    QueryResult getComRecords(QueryFilter filter, Page page, boolean optimized);

    /**
     * Retrieves communication records for the specified filter and page without optimization.
     * <p>
     * For sessions opened by a user, {@code loginName} is not required. This
     * method will return {@code null} if invoked from an administrator session.
     * 
     * @param filter the filter describing the query criteria
     * @param page   the page description
     * @return a {@link QueryResult} containing the matching com records, or {@code null} otherwise
     */
    QueryResult getComRecords(QueryFilter filter, Page page);

    /**
     * Retrieves communication records for the specified filter.
     * <p>
     * For sessions opened by a user, {@code loginName} is not required. This
     * method will return {@code null} if invoked from an administrator session.
     * 
     * @param filter the filter describing the query criteria
     * @return a {@link QueryResult} containing the matching com records, or {@code null} otherwise
     */
    QueryResult getComRecords(QueryFilter filter);

    /**
     * Retrieves a specific communication record by its identifier.
     * <p>
     * If the session is user-specific, {@code loginName} is ignored. If the session
     * is opened by an administrator, {@code loginName} is required.
     * 
     * @param recordId  the com record identifier
     * @param loginName the target user's login name
     * @return the {@link ComRecord} with the given ID, or {@code null} if not found or on error
     */
    ComRecord getComRecord(long recordId, String loginName);

    /**
     * Retrieves a specific communication record by its identifier.
     * <p>
     * For sessions opened by a user, this method can be used directly. Returns
     * {@code null} if invoked from an administrator session.
     * 
     * @param recordId the com record identifier
     * @return the {@link ComRecord} with the given ID, or {@code null} if not found or on error
     */
    ComRecord getComRecord(long recordId);

    /**
     * Deletes a specific communication record by its identifier.
     * <p>
     * If the session is user-specific, {@code loginName} is ignored. If the session
     * is opened by an administrator, {@code loginName} is required.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised when
     * the deletion succeeds.
     * 
     * @param recordId  the com record identifier
     * @param loginName the target user's login name
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecord(long recordId, String loginName);

    /**
     * Deletes a specific communication record by its identifier.
     * <p>
     * For sessions opened by a user, this method can be used directly. Returns
     * {@code false} if invoked from an administrator session.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised when
     * the deletion succeeds.
     * 
     * @param recordId the com record identifier
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecord(long recordId);

    /**
     * Deletes multiple communication records matching the specified filter.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} event
     * listing the deleted records.
     * 
     * @param filter    the filter describing which records to delete
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return {@code true} if deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(QueryFilter filter, String loginName);

    /**
     * Deletes multiple communication records matching the specified filter.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} event
     * listing the deleted records.
     * <p>
     * Returns {@code false} if invoked from an administrator session.
     * 
     * @param filter the filter describing which records to delete
     * @return {@code true} if deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(QueryFilter filter);

    /**
     * Deletes multiple communication records by their identifiers.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} event
     * listing the deleted records.
     * 
     * @param recordIds the list of com record IDs
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return {@code true} if deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(Collection<Long> recordIds, String loginName);

    /**
     * Deletes multiple communication records by their identifiers.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} event
     * listing the deleted records.
     * <p>
     * Returns {@code false} if invoked from an administrator session.
     * 
     * @param recordIds the list of com record IDs
     * @return {@code true} if deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(Collection<Long> recordIds);

    /**
     * Acknowledges a list of communication records.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} event
     * listing the acknowledged records.
     * 
     * @param recordIds the list of com record IDs
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return {@code true} if acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecords(Collection<Long> recordIds, String loginName);

    /**
     * Acknowledges a list of communication records.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} event
     * listing the acknowledged records.
     * <p>
     * Returns {@code false} if invoked from an administrator session.
     * 
     * @param recordIds the list of com record IDs
     * @return {@code true} if acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecords(Collection<Long> recordIds);

    /**
     * Acknowledges a single communication record.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} event.
     * 
     * @param recordId  the com record ID
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return {@code true} if acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecord(long recordId, String loginName);

    /**
     * Acknowledges a single communication record.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} event.
     * <p>
     * Returns {@code false} if invoked from an administrator session.
     * 
     * @param recordId the com record ID
     * @return {@code true} if acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecord(long recordId);

    /**
     * Unacknowledges a list of communication records.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} event.
     * 
     * @param recordIds the list of com record IDs
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return {@code true} if unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecords(Collection<Long> recordIds, String loginName);

    /**
     * Unacknowledges a list of communication records.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} event.
     * <p>
     * Returns {@code false} if invoked from an administrator session.
     * 
     * @param recordIds the list of com record IDs
     * @return {@code true} if unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecords(Collection<Long> recordIds);

    /**
     * Unacknowledges a single communication record.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} event.
     * 
     * @param recordId  the com record ID
     * @param loginName the target user's login name (ignored if session is user-specific)
     * @return {@code true} if unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecord(long recordId, String loginName);

    /**
     * Unacknowledges a single communication record.
     * <p>
     * Raises an {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} event.
     * <p>
     * Returns {@code false} if invoked from an administrator session.
     * 
     * @param recordId the com record ID
     * @return {@code true} if unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecord(long recordId);
}
