/*
* Copyright 2021 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this
* software and associated documentation files (the "Software"), to deal in the Software
* without restriction, including without limitation the rights to use, copy, modify, merge,
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
* to whom the Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in all copies or
* substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
package com.ale.o2g;


import java.util.Collection;

import com.ale.o2g.internal.services.IService;
import com.ale.o2g.types.comlog.ComRecord;
import com.ale.o2g.types.comlog.Page;
import com.ale.o2g.types.comlog.QueryFilter;
import com.ale.o2g.types.comlog.QueryResult;

/**
 * The {@code CommunicationLogService} provides operations to retrieve, manage,
 * and manipulate a user's communication log (com records).
 * <p>
 * Using this service requires having a <b>TELEPHONY_ADVANCED</b> license.
 * <p>
 * Communication records are generated by the O2G server and provide detailed
 * information about calls, participants, call outcomes, and durations. The
 * communication log has a depth of 100 records maximum per user; when the limit
 * is reached, the oldest records are removed.
 * <p>
 * Acknowledgement and unacknowledgement of an incoming missed call using O2G is
 * <b>NOT synchronized</b> with the OmniPCX Enterprise.
 * <p>
 * Most methods support sessions opened either by a regular user or by an
 * administrator. If the session has been opened for a user, the {@code loginName}
 * parameter is ignored, but it is mandatory if the session has been opened by an
 * administrator.
 */
public interface CommunicationLogService extends IService {

    /**
     * Retrieves communication records based on the specified {@link QueryFilter},
     * with pagination support and optional optimization.
     * <p>
     * If {@code optimized} is {@code true}, the full identity of a participant is
     * returned only the first time it appears in the records. Subsequent occurrences
     * of the same participant will only include minimal identification (e.g., phone number).
     * <p>
     * The {@link Page} parameter allows querying the communication log page by page.
     * The returned {@link QueryResult} includes the records, paging information, and
     * the total number of matching records.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     *
     * @param filter    the filter describing the query criteria
     * @param page      the page description
     * @param optimized {@code true} to enable optimization
     * @param loginName the target user's login name
     * @return a {@link QueryResult} containing the matching com records, or {@code null} in case of error
     */
    QueryResult getComRecords(QueryFilter filter, Page page, boolean optimized, String loginName);

    /**
     * Retrieves communication records based on the specified filter and page,
     * with optional optimization.
     * <p>
     * If {@code optimized} is {@code true}, the full identity of a participant is
     * returned only the first time it appears in the records. Subsequent occurrences
     * of the same participant will only include minimal identification (e.g., phone number).
     * <p>
     * The {@link Page} parameter allows querying the communication log page by page.
     * The returned {@link QueryResult} includes the records, paging information, and
     * the total number of matching records.
     * <p>
     * This method will fail and return {@code null} if it is invoked from a session
     * opened by an administrator.
     *
     * @param filter    the filter describing the query criteria
     * @param page      the page description
     * @param optimized {@code true} to enable optimization
     * @return a {@link QueryResult} containing the matching com records, or {@code null} in case of error
     */
    QueryResult getComRecords(QueryFilter filter, Page page, boolean optimized);

    /**
     * Retrieves communication records for the specified filter and page without
     * optimization.
     * <p>
     * This method will fail and return {@code null} if it is invoked from a session
     * opened by an administrator.
     *
     * @param filter the filter describing the query criteria
     * @param page   the page description
     * @return a {@link QueryResult} containing the matching com records, or {@code null} in case of error
     */
    QueryResult getComRecords(QueryFilter filter, Page page);

    /**
     * Retrieves communication records for the specified filter.
     * <p>
     * This method will fail and return {@code null} if it is invoked from a session
     * opened by an administrator.
     *
     * @param filter the filter describing the query criteria
     * @return a {@link QueryResult} containing the matching com records, or {@code null} in case of error
     */
    QueryResult getComRecords(QueryFilter filter);

    /**
     * Retrieves a specific communication record by its identifier.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     *
     * @param recordId  the com record identifier
     * @param loginName the target user's login name
     * @return the {@link ComRecord} with the given identifier, or {@code null} if not found or in case of error
     */
    ComRecord getComRecord(long recordId, String loginName);

    /**
     * Retrieves a specific communication record by its identifier.
     * <p>
     * This method will fail and return {@code null} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordId the com record identifier
     * @return the {@link ComRecord} with the given identifier, or {@code null} if not found or in case of error
     */
    ComRecord getComRecord(long recordId);

    /**
     * Deletes a specific communication record by its identifier.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised when
     * the deletion succeeds.
     *
     * @param recordId  the com record identifier
     * @param loginName the target user's login name
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecord(long recordId, String loginName);

    /**
     * Deletes a specific communication record by its identifier.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised when
     * the deletion succeeds.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordId the com record identifier
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecord(long recordId);

    /**
     * Deletes multiple communication records matching the specified filter.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised listing
     * the deleted records.
     *
     * @param filter    the filter describing which records to delete
     * @param loginName the target user's login name
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(QueryFilter filter, String loginName);

    /**
     * Deletes multiple communication records matching the specified filter.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised listing
     * the deleted records.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param filter the filter describing which records to delete
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(QueryFilter filter);

    /**
     * Deletes multiple communication records by their identifiers.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised listing
     * the deleted records.
     *
     * @param recordIds the collection of com record identifiers to delete
     * @param loginName the target user's login name
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(Collection<Long> recordIds, String loginName);

    /**
     * Deletes multiple communication records by their identifiers.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsDeletedEvent} is raised listing
     * the deleted records.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordIds the collection of com record identifiers to delete
     * @return {@code true} if the deletion was successful; {@code false} otherwise
     */
    boolean deleteComRecords(Collection<Long> recordIds);

    /**
     * Acknowledges a list of communication records.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} is raised listing
     * the acknowledged records.
     *
     * @param recordIds the collection of com record identifiers to acknowledge
     * @param loginName the target user's login name
     * @return {@code true} if the acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecords(Collection<Long> recordIds, String loginName);

    /**
     * Acknowledges a list of communication records.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} is raised listing
     * the acknowledged records.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordIds the collection of com record identifiers to acknowledge
     * @return {@code true} if the acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecords(Collection<Long> recordIds);

    /**
     * Acknowledges a single communication record.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} is raised when the
     * acknowledgment succeeds.
     *
     * @param recordId  the com record identifier
     * @param loginName the target user's login name
     * @return {@code true} if the acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecord(long recordId, String loginName);

    /**
     * Acknowledges a single communication record.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsAckEvent} is raised when the
     * acknowledgment succeeds.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordId the com record identifier
     * @return {@code true} if the acknowledgment succeeded; {@code false} otherwise
     */
    boolean acknowledgeComRecord(long recordId);

    /**
     * Unacknowledges a list of communication records.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} is raised listing
     * the unacknowledged records.
     *
     * @param recordIds the collection of com record identifiers to unacknowledge
     * @param loginName the target user's login name
     * @return {@code true} if the unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecords(Collection<Long> recordIds, String loginName);

    /**
     * Unacknowledges a list of communication records.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} is raised listing
     * the unacknowledged records.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordIds the collection of com record identifiers to unacknowledge
     * @return {@code true} if the unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecords(Collection<Long> recordIds);

    /**
     * Unacknowledges a single communication record.
     * <p>
     * If the session has been opened for a user, the {@code loginName} parameter is
     * ignored, but it is mandatory if the session has been opened by an administrator.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} is raised when the
     * unacknowledgment succeeds.
     *
     * @param recordId  the com record identifier
     * @param loginName the target user's login name
     * @return {@code true} if the unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecord(long recordId, String loginName);

    /**
     * Unacknowledges a single communication record.
     * <p>
     * An {@link com.ale.o2g.events.comlog.OnComRecordsUnAckEvent} is raised when the
     * unacknowledgment succeeds.
     * <p>
     * This method will fail and return {@code false} if it is invoked from a session
     * opened by an administrator.
     *
     * @param recordId the com record identifier
     * @return {@code true} if the unacknowledgment succeeded; {@code false} otherwise
     */
    boolean unacknowledgeComRecord(long recordId);
}
