/*
* Copyright 2025 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this 
* software and associated documentation files (the "Software"), to deal in the Software 
* without restriction, including without limitation the rights to use, copy, modify, merge, 
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons 
* to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or 
* substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
package com.ale.o2g.types.recording;

/**
 * Represents an active call on a recordable device.
 * <p>
 * A call is uniquely identified by its {@link #callRef}, which is generated by the O2G server.
 */
public class ActiveCall {

    private String callRef;
    private RecordingState recordingState;
    private RecordingAction action;
    
    /**
     * Returns the reference of this call.
     *
     * @return the unique call reference
     */
    public String getCallRef() {
        return callRef;
    }
    
    /**
     * Returns the recording state of this call.
     *
     * @return the recording state
     */
    public RecordingState getRecordingState() {
        return recordingState;
    }
    
    /**
     * Returns the possible recording action for this call.
     *
     * @return the recording action
     */
    public RecordingAction getAction() {
        return action;
    }
}
