/*
* Copyright 2025 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this 
* software and associated documentation files (the "Software"), to deal in the Software 
* without restriction, including without limitation the rights to use, copy, modify, merge, 
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons 
* to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or 
* substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
package com.ale.o2g.types.ccstats;

import com.google.gson.annotations.SerializedName;

/**
 * {@code AgentAttributes} defines the set of statistical attributes available
 * for a CCD agent.
 * <p>
 * These attributes are used in reports generated by
 * {@link com.ale.o2g.CallCenterStatisticsService CallCenterStatisticsService} to provide insight into agent activity,
 * performance, and call handling.
 * <p>
 * Attributes are grouped into:
 * <ul>
 * <li><b>Counts</b> - number of calls, pickups, refusals, etc.</li>
 * <li><b>Durations</b> - total and average times, expressed in
 * {@code hh:mm:ss}.</li>
 * <li><b>Percentages</b> - proportion of time spent in various agent
 * states.</li>
 * </ul>
 *
 * <p>
 * <b>Note:</b> The {@link #ALL} attribute is intended for testing only and
 * should not be used in production contexts.
 *
 * @since 2.7.4
 */
public enum AgentAttributes {

    /** 
     * Number of rotating timeouts experienced by the agent.
     * <p>
     * A rotating timeout typically occurs when a call is offered to an agent 
     * but is not answered within the allotted time before being routed elsewhere.
     */
    nbRotating,

    /** 
     * Number of calls successfully answered by the agent. 
     */
    nbPickedUp,

    /** 
     * Number of call pickup actions initiated by the agent. 
     * <p>
     * This includes manual pickups of ringing calls for other agents or extensions.
     */
    nbPickup,

    /** 
     * Number of internal outgoing calls initiated by the agent that are not 
     * associated with an Automatic Call Distribution (ACD) queue. 
     */
    nbLocalOutNonAcd,

    /** 
     * Number of external outgoing calls initiated by the agent that are not 
     * associated with an Automatic Call Distribution (ACD) queue. 
     */
    @SerializedName("nbExtOutNonacd")
    nbExtOutNonAcd,

    /** 
     * Number of ACD calls that were presented (rang) to the agent.
     */
    nbRingAcd,

    /** 
     * Number of calls during which the agent initiated a help or assistance request. 
     */
    nbHelp,

    /** 
     * Number of internal incoming calls received by the agent that are not 
     * associated with an Automatic Call Distribution (ACD) queue. 
     */
    @SerializedName("nbLocInNonacd")
    nbLocInNonAcd,

    /** 
     * Number of non-ACD external incoming calls received directly by the agent.
     * <p>
     * These are calls from external sources not routed through an 
     * Automatic Call Distribution (ACD) queue.
     */
    @SerializedName("nbExtInNonacdDirect")
    nbExtInNonAcdDirect,

    /** 
     * Number of non-ACD external incoming calls transferred to the agent.
     * <p>
     * Includes calls initially received by another extension and then 
     * redirected to the agent.
     */
    @SerializedName("nbExtInNonacdTransferred")
    nbExtInNonAcdTransferred,

    /** 
     * Number of ACD calls handled (served) by the agent without 
     * an associated transaction code.
     */
    nbServedWOCode,

    /** 
     * Number of ACD calls handled (served) by the agent with 
     * an associated transaction code.
     */
    nbServedWCode,

    /** 
     * Number of ACD calls served too quickly.
     * <p>
     * This typically refers to calls with a handling duration below 
     * a configured threshold.
     */
    nbAcdQuickServed,

    /** 
     * Number of non-ACD external incoming calls successfully served 
     * by the agent.
     */
    @SerializedName("nbExtinNonacdServed")
    nbExtInNonAcdServed,

    /** 
     * Number of non-ACD external incoming calls served too quickly.
     * <p>
     * This typically indicates calls that ended before meaningful 
     * interaction occurred.
     */
    @SerializedName("nbExtinNonacdQuickServed")
    nbExtInNonAcdQuickServed,

    /** 
     * Number of outgoing ACD calls initiated by the agent.
     */
    nbOutAcd,

    /** 
     * Number of outgoing ACD calls that were answered by the destination party.
     */
    nbOutAcdAnswered,

    /** 
     * Number of calls currently or cumulatively in the wrap-up state.
     * <p>
     * The wrap-up period refers to post-call processing time after 
     * a conversation ends.
     */
    nbOnWrapup,

    /** 
     * Total ringing duration for ACD calls that were served.
     */
    ringAcdServedTDur,

    /** 
     * Average ringing duration for ACD calls that were served.
     */
    ringAcdServedADur,

    /** 
     * Total ringing duration for non-ACD external incoming calls that were served.
     */
    ringInNonAcdExtServedTDur,

    /** 
     * Average ringing duration for non-ACD external incoming calls that were served.
     */
    ringInNonAcdExtServedADur,

    /** 
     * Total ringing duration for ACD calls.
     */
    ringAcdTDur,

    /** 
     * Average ringing duration for ACD calls.
     */
    ringAcdADur,

    /** 
     * Total ringing duration for non-ACD external incoming calls.
     */
    ringInNonAcdExtTDur,

    /** 
     * Average ringing duration for non-ACD external incoming calls.
     */
    ringInNonAcdExtADur,

    /** 
     * Total ringing duration for all calls.
     */
    ringTDur,

    /** 
     * Average ringing duration for all calls.
     */
    ringADur,

    /** 
     * Total conversation duration for ACD calls.
     */
    convAcdTDur,

    /** 
     * Average conversation duration for ACD calls.
     */
    convAcdADur,

    /** 
     * Total wrap-up duration for all calls served.
     */
    wrapupAcdTDur,

    /** 
     * Total conversation duration for internal outgoing non-ACD calls.
     */
    @SerializedName("convLocOutNonacdTDur")
    convLocOutNonAcdTDur,

    /** 
     * Average conversation duration for internal outgoing non-ACD calls.
     */
    @SerializedName("convLocOutNonacdADur")
    convLocOutNonAcdADur,

    /** 
     * Total conversation duration for external outgoing calls.
     */
    convExtOutTDur,

    /** 
     * Average conversation duration for external outgoing calls.
     */
    convExtOutADur,

    /** 
     * Total conversation duration for non-ACD internal incoming calls.
     */
    @SerializedName("convLocInNonacdTDur")
    convLocInNonAcdTDur,

    /** 
     * Average conversation duration for non-ACD internal incoming calls.
     */
    @SerializedName("convLocInNonacdADur")
    convLocInNonAcdADur,

    /** 
     * Total conversation duration for non-ACD external incoming calls.
     */
    @SerializedName("convExtInNonacdTDur")
    convExtInNonAcdTDur,

    /** 
     * Average conversation duration for non-ACD external incoming calls.
     */
    @SerializedName("convExtInNonacdADur")
    convExtInNonAcdADur,

    /** 
     * Total call processing duration for outgoing ACD calls.
     */
    outAcdCommTDur,

    /** 
     * Average call processing duration for outgoing ACD calls.
     */
    outAcdCommADur,

    /** 
     * Total conversation duration for outgoing ACD calls.
     */
    outAcdConvTDur,

    /** 
     * Average conversation duration for outgoing ACD calls.
     */
    outAcdConvADur,

    /** 
     * Total transaction phase duration for outgoing ACD calls.
     */
    outAcdTransactTDur,

    /** 
     * Average transaction phase duration for outgoing ACD calls.
     */
    outAcdTransactADur,

    /** 
     * Total wrap-up duration for outgoing ACD calls.
     */
    outAcdWrapupTDur,

    /** 
     * Average wrap-up duration for outgoing ACD calls.
     */
    outAcdWrapupADur,

    /** 
     * Total pause duration for outgoing ACD calls.
     */
    outAcdPauseTDur,

    /** 
     * Average pause duration for outgoing ACD calls.
     */
    outAcdPauseADur,

    /** 
     * Total wrap-up duration while the agent was idle.
     */
    wrapUpIdleTDur,

    /** 
     * Total conversation duration during wrap-up.
     */
    callOnWrapupTDur,

    /** 
     * Total busy time during wrap-up.
     */
    busyOnWrapupTDur,

    /** 
     * Total busy time for the agent.
     */
    busyTDur,

    /** 
     * Percentage of total time the agent was logged out.
     */
    loggedOutPerTime,

    /** 
     * Percentage of time the agent was logged in but not assigned to a call.
     */
    notAssignedPerTime,

    /** 
     * Percentage of time the agent was logged in and assigned to a call.
     */
    assignedPerTime,

    /** 
     * Percentage of time the agent was in withdrawal (unavailable for calls).
     */
    withdrawPerTime,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 1.
     */
    withdrawPerTimeCause1,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 2.
     */
    withdrawPerTimeCause2,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 3.
     */
    withdrawPerTimeCause3,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 4.
     */
    withdrawPerTimeCause4,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 5.
     */
    withdrawPerTimeCause5,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 6.
     */
    withdrawPerTimeCause6,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 7.
     */
    withdrawPerTimeCause7,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 8.
     */
    withdrawPerTimeCause8,

    /** 
     * Percentage of time the agent was in withdrawal due to cause 9.
     */
    withdrawPerTimeCause9,

    /** 
     * Number of pilots the agent served calls for.
     */
    nbPilots,

    /** 
     * Number of ACD calls served by the agent.
     */
    nbAcdServedCalls,

    /** 
     * Number of incoming ACD calls served by the agent.
     */
    nbAcdInServedCalls,

    /** 
     * Number of incoming calls received directly by the pilot and served.
     */
    nbInCallsReceivedByPilot,

    /** 
     * Number of outgoing ACD calls served by the agent.
     */
    nbAcdOutServedCalls,

    /** 
     * Total number of ACD calls not served by the agent.
     */
    nbTotNonServedCalls,

    /** 
     * Number of incoming ACD calls not served by the agent.
     */
    nbInNonServedCalls,

    /** 
     * Number of incoming ACD calls picked up but not served.
     */
    @SerializedName("nbPickedupCalls")
    nbPickedUpCalls,

    /** 
     * Number of incoming ACD calls refused by the agent.
     */
    nbRefusedCalls,

    /** 
     * Number of outgoing ACD calls not served by the agent.
     */
    nbAcdOutNonServedCalls,

    /** 
     * Total number of non-ACD calls received by the agent.
     */
    @SerializedName("nbTotNonAcdreceivedCalls")
    nbTotNonAcdReceivedCalls,

    /** 
     * Number of incoming non-ACD calls received by the agent.
     */
    nbInNonAcdCalls,

    /** 
     * Number of outgoing non-ACD calls initiated by the agent.
     */
    nbOutNonAcdCalls,

    /** 
     * Duration the agent was assigned to a group but not in withdrawal.
     */
    assignedNotWithdrawDur,

    /** 
     * Total duration the agent was in withdrawal.
     */
    withdrawDur,

    /** 
     * Duration the agent spent in manual wrap-up.
     */
    manuWrapupDur,

    /** 
     * Duration the agent was in an unreachable state.
     */
    unreachableDur,

    /** 
     * Total duration spent in non-ACD work.
     */
    nonAcdWorkTDur,

    /** 
     * Average duration spent in non-ACD work.
     */
    nonAcdWorkADur,

    /** 
     * Total duration spent in ACD work.
     */
    acdWorkTDur,

    /** 
     * Average duration spent in ACD work.
     */
    acdWorkADur,

    /** 
     * Total duration spent in incoming ACD work.
     */
    acdWorkInTDur,

    /** 
     * Average duration spent in incoming ACD work.
     */
    acdWorkInADur,

    /** 
     * Total conversation duration in incoming ACD work.
     */
    acdWorkInConvTDur,

    /** 
     * Average conversation duration in incoming ACD work.
     */
    acdWorkInConvADur,

    /** 
     * Total ringing duration in incoming ACD work.
     */
    acdWorkInRingTDur,

    /** 
     * Average ringing duration in incoming ACD work.
     */
    acdWorkInRingADur,

    /** 
     * Total wrap-up duration in incoming ACD work.
     */
    acdWorkInWrapupTDur,

    /** 
     * Average wrap-up duration in incoming ACD work.
     */
    acdWorkInWrapupADur,

    /** 
     * Total duration spent in outgoing ACD work.
     */
    acdWorkOutTDur,

    /** 
     * Average duration spent in outgoing ACD work.
     */
    acdWorkOutADur,

    /** 
     * Total conversation duration in outgoing ACD work.
     */
    acdWorkOutConvTDur,

    /** 
     * Average conversation duration in outgoing ACD work.
     */
    acdWorkOutConvADur,

    /** 
     * Total wrap-up duration in outgoing ACD work.
     */
    acdWorkOutWrapupTDur,

    /** 
     * Average wrap-up duration in outgoing ACD work.
     */
    acdWorkOutWrapupADur,

    /** 
     * Total conversation duration for incoming ACD calls.
     */
    acdInConvTDur,

    /** 
     * Average conversation duration for incoming ACD calls.
     */
    acdInConvADur,

    /** 
     * Total conversation duration for outgoing ACD calls.
     */
    acdOutConvTDur,

    /** 
     * Average conversation duration for outgoing ACD calls.
     */
    acdOutConvADur,

    /** All attributes (test purposes only; not for production use). */
    ALL
}
