/*
* Copyright 2025 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this 
* software and associated documentation files (the "Software"), to deal in the Software 
* without restriction, including without limitation the rights to use, copy, modify, merge, 
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons 
* to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or 
* substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
package com.ale.o2g.types.ccstats;

/**
 * {@code PilotAbandonedCallAttribute} enumerates tthe set of statistical attributes
 * available for abandoned calls on a CCD pilot.
 * <p>
 * These attributes are used in reports generated by `CallCenterStatisticsService`
 * to provide insight into call abandonment patterns on a pilot, including when
 * and where in the call flow the caller hung up.
 * <p>
 * The special attribute {@link #ALL} includes all available attributes and is
 * mainly intended for testing or bulk retrieval purposes.
 * 
 * @since 2.7.5
 */
public enum PilotAbandonedCallsAttributes {

    /** Total time in seconds the caller waited before hanging up. */
    waitingTime,

    /** The name of the pilot. */
    pilotName,

    /** The number of the pilot. */
    pilotNumber,

    /** The phone number of the caller. */
    callerNumber,

    /** The caller abandoned during the greeting voice guide. */
    abandonedOnGreetingVG,

    /** The caller abandoned during the 1st waiting voice guide. */
    abandonedOn1stWaitingVG,

    /** The caller abandoned during the 2nd waiting voice guide. */
    abandonedOn2ndWaitingVG,

    /** The caller abandoned during the 3rd waiting voice guide. */
    abandonedOn3rdWaitingVG,

    /** The caller abandoned during the 4th waiting voice guide. */
    abandonedOn4thWaitingVG,

    /** The caller abandoned during the 5th waiting voice guide. */
    abandonedOn5thWaitingVG,

    /** The caller abandoned during the 6th waiting voice guide. */
    abandonedOn6thWaitingVG,

    /** The caller abandoned while ringing an agent. */
    abandonedOnRinging,

    /** The caller abandoned during the general forwarding voice guide. */
    abandonedOnGeneralFwdVG,

    /** The caller abandoned during the blocked voice guide. */
    abandonedOnBlockedVG,

    /** The caller abandoned while waiting on a direct call to a busy agent. */
    abandonedOnDirectCallWaiting,

    /** All attributes — for use in context creation only. */
    ALL
}
